#!/bin/bash


figlet -f slant "Portal RL"


welcome1="Welcome to Portal RL - A user friendly ednvironment for learning"
welcome2="and deploying reinforcement learning environments and agents"
echo $welcome1
echo $welcome2

python3 portalrl.py
